[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
optimizer = true
optimizer_runs = 200


[rpc_endpoints]
bsc = "${BINANCE_RPC_URL}"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config