
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0

autofetch_sources: true

compiler:
  solc:
    version: 0.8.17
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
      # - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0"



dotenv: .env

networks:
  default: development
  development:
    verify: False
    chainID: 1337
  sepolia:
    verify: False
  ganache:
    verify: False
wallets:
  # from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}